# Generated by Django 4.0.3 on 2022-03-28 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(unique=True)),
                ('state', models.CharField(choices=[('INSTALLED', 'Installed'), ('UNINSTALLED', 'Uninstalled')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUserRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='app.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubUserAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='app.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('repo_name', models.CharField(max_length=150)),
                ('repo_full_name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.githubappinstallation')),
            ],
        ),
        migrations.CreateModel(
            name='GithubRepoMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial')], max_length=20)),
                ('code_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_repos', to='app.githubrepository')),
                ('documentation_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_repos', to='app.githubrepository')),
            ],
        ),
        migrations.CreateModel(
            name='GithubInstallationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_app_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.githubappinstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='githubappinstallation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.githubuser'),
        ),
    ]
