# Generated by Django 4.0.3 on 2022-03-30 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(db_index=True, unique=True)),
                ('state', models.CharField(choices=[('INSTALLED', 'Installed'), ('UNINSTALLED', 'Uninstalled')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.BigIntegerField()),
                ('pr_number', models.BigIntegerField()),
                ('pr_head_commit_sha', models.CharField(max_length=40)),
                ('pr_head_tree_sha', models.CharField(max_length=40)),
                ('pr_head_modified_on', models.DateTimeField()),
                ('pr_head_commit_message', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_request_status', models.CharField(choices=[('NOT_CONNECTED', 'Not Connected'), ('CONNECTED', 'Connected'), ('APPROVED', 'Approved')], default='NOT_CONNECTED', max_length=20)),
                ('code_pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_code', to='app.githubpullrequest')),
                ('documentation_pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitored_documentation', to='app.githubpullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUserRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='app.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubUserAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='app.githubuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('repo_name', models.CharField(max_length=150)),
                ('repo_full_name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.githubappinstallation')),
            ],
        ),
        migrations.CreateModel(
            name='GithubRepoMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial')], max_length=20)),
                ('code_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_repos', to='app.githubrepository')),
                ('documentation_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentation_repos', to='app.githubrepository')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.githubappinstallation')),
            ],
        ),
        migrations.CreateModel(
            name='GithubInstallationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('github_app_installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.githubappinstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='githubappinstallation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.githubuser'),
        ),
        migrations.CreateModel(
            name='GithubCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.BigIntegerField(blank=True, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('head_sha', models.CharField(max_length=40)),
                ('force_approve', models.BooleanField(blank=True, default=None, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='app.monitoredpullrequest')),
            ],
            options={
                'unique_together': {('head_sha', 'pull_request')},
            },
        ),
    ]
