# Generated by Django 4.0.3 on 2022-03-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepomap',
            name='integration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.githubappinstallation'),
            preserve_default=False,
        ),
    ]
