# Generated by Django 4.0.3 on 2022-03-29 07:49

from django.db import models, migrations

from django.core.management import call_command


def update_permissions(schema, group):
    call_command("update_permissions")


def apply_migration(apps, schema_editor):
    # Add, change, delete, view
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    required_permissions = [
        "view_githubappinstallation",
        "change_githubappinstallation",
        "view_githubrepomap",
        "add_githubrepomap",
        "change_githubrepomap",
        # "delete_githubrepomap",
        # "view_documentationrepopullrequest",
        "view_coderepopullrequest",
        "change_coderepopullrequest",
        "view_githubcheckrun",
        "change_githubcheckrun",
    ]
    all_perms = Permission.objects.filter(codename__in=required_permissions)
    (new_group, _) = Group.objects.get_or_create(name="github_user")
    for perm in all_perms:
        new_group.permissions.add(perm)


def revert_migration(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            update_permissions, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(apply_migration, revert_migration),
    ]
