# Generated by Django 4.0.3 on 2022-03-28 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_githubrepomap_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRepoPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.BigIntegerField()),
                ('pr_number', models.BigIntegerField()),
                ('check_approved', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.BigIntegerField(blank=True, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('head_sha', models.CharField(max_length=40)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='app.coderepopullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationRepoPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.BigIntegerField()),
                ('pr_number', models.BigIntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_repo_prs', to='app.githubrepository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coderepopullrequest',
            name='documentation_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.documentationrepopullrequest'),
        ),
        migrations.AddField(
            model_name='coderepopullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_repo_prs', to='app.githubrepository'),
        ),
    ]
