# Generated by Django 4.0.3 on 2022-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220329_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepomap',
            name='sync_history',
            field=models.BooleanField(default=False),
        ),
    ]
