# Generated by Django 4.0.3 on 2022-03-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_githubrepomap_sync_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepomap',
            name='sync_history',
        ),
    ]
