# Generated by Django 4.0.3 on 2022-03-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_githubrepomap_sync_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubpullrequest',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.githubrepository'),
            preserve_default=False,
        ),
    ]
