# Generated by Django 4.0.3 on 2022-04-05 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_head_sha_githubcheckrun_run_sha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubpullrequest',
            name='pr_head_tree_sha',
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_body',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 10, 41, 47, 76174, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_merged_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_state',
            field=models.CharField(default='open', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='githubpullrequest',
            name='pr_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 10, 42, 9, 27732, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='monitoredpullrequest',
            name='code_pull_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_code', to='app.githubpullrequest'),
        ),
        migrations.AlterField(
            model_name='monitoredpullrequest',
            name='pull_request_status',
            field=models.CharField(choices=[('NOT_CONNECTED', 'Not Connected'), ('APPROVAL_PENDING', 'Approval Pending'), ('STALE_CODE', 'Stale Code'), ('STALE_APPROVAL', 'Stale Approval'), ('APPROVED', 'Approved')], default='NOT_CONNECTED', max_length=20),
        ),
    ]
