# Generated by Django 4.0.3 on 2022-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_githubpullrequest_pr_head_tree_sha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_head_modified_on',
            field=models.DateTimeField(null=True),
        ),
    ]
