# Generated by Django 4.0.3 on 2022-04-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_githubpullrequest_pr_head_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
