# Generated by Django 4.0.3 on 2022-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_githubpullrequest_pr_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_head_modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
