# Generated by Django 4.0.3 on 2022-04-12 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_githubpullrequest_pr_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredpullrequest',
            name='pull_request_status',
            field=models.CharField(choices=[('NOT_CONNECTED', 'Not Connected'), ('APPROVAL_PENDING', 'Approval Pending'), ('STALE_CODE', 'Stale Code'), ('STALE_APPROVAL', 'Stale Approval'), ('APPROVED', 'Approved'), ('MANUALLY_APPROVED', 'Manual Approval')], default='NOT_CONNECTED', max_length=20),
        ),
        migrations.CreateModel(
            name='GithubAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.githubuser')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.githubappinstallation')),
            ],
            options={
                'unique_together': {('installation', 'github_user')},
            },
        ),
    ]
