# Generated by Django 4.0.3 on 2022-04-12 07:15

from django.db import migrations, models
import django.db.models.deletion


def migrate_pr_integrations(apps, schema_editor):
    # Add, change, delete, view
    # Group = apps.get_model("auth", "Group")
    MonitoredPullRequest = apps.get_model("app", "MonitoredPullRequest")
    # GithubAppInstallation = apps.get_model("app", "GithubAppInstallation")
    GithubRepoMap = apps.get_model("app", "GithubRepoMap")
    for monitored_pr_instance in MonitoredPullRequest.objects.all():
        code_pull_request = monitored_pr_instance.code_pull_request
        # documentation_pull_request = monitored_pr_instance.documentation_pull_request
        grm = GithubRepoMap.objects.filter(
            code_repo=code_pull_request.repository,
            # documentation_repo=documentation_pull_request.repository,
        ).last()
        if grm is None:
            assert False, "Exception: grm is None"
        monitored_pr_instance.integration = grm.integration
        monitored_pr_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_monitoredpullrequest_pull_request_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredpullrequest",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.githubappinstallation",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="githubrepomap",
            unique_together={("integration", "code_repo", "documentation_repo")},
        ),
        migrations.AlterUniqueTogether(
            name="monitoredpullrequest",
            unique_together={("code_pull_request", "documentation_pull_request")},
        ),
        migrations.RunPython(migrate_pr_integrations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="monitoredpullrequest",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.githubappinstallation",
            ),
        ),
    ]
