# Generated by Django 4.0.3 on 2022-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_githubloginstate_githubappuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='githubpullrequest',
            name='pr_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
