# Generated by Django 4.0.3 on 2022-04-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_pr_approver(apps, schema_editor):
    # Add, change, delete, view
    # Group = apps.get_model("auth", "Group")
    MonitoredPullRequest = apps.get_model("app", "MonitoredPullRequest")
    PrApproval = apps.get_model("app", "PrApproval")
    for monitored_pr in MonitoredPullRequest.objects.filter(
        pull_request_status__in=["APPROVED", "MANUALLY_APPROVED"]
    ):
        PrApproval.objects.create(
            monitored_pull_request=monitored_pr,
            approver=monitored_pr.integration.creator.user,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0016_alter_githubpullrequest_pr_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitored_pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.monitoredpullrequest",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_pr_approver, migrations.RunPython.noop),
    ]
