# Generated by Django 4.0.4 on 2022-05-25 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_githubmarketplaceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.BigIntegerField(db_index=True, unique=True)),
                ('state', models.CharField(choices=[('INSTALLED', 'Installed'), ('UNINSTALLED', 'Uninstalled'), ('SUSPENDED', 'Suspended')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_id', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('social_app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialaccount.socialapp')),
            ],
            options={
                'unique_together': {('social_app', 'installation_id')},
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinstallation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('installation', 'user')},
            },
        ),
        migrations.RenameModel(
            old_name='GithubPullRequest',
            new_name='PullRequest',
        ),
        migrations.RenameModel(
            old_name='GithubCheckRun',
            new_name='PullRequestCheck',
        ),
        migrations.RemoveField(
            model_name='githubappinstallation',
            name='creator',
        ),
        migrations.AlterUniqueTogether(
            name='githubappuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='githubappuser',
            name='github_user',
        ),
        migrations.RemoveField(
            model_name='githubappuser',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='githubinstallationtoken',
            name='github_app_installation',
        ),
        migrations.DeleteModel(
            name='GithubLoginState',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='githubuseraccesstoken',
            name='github_user',
        ),
        migrations.RemoveField(
            model_name='githubuserrefreshtoken',
            name='github_user',
        ),
        migrations.RenameModel(
            old_name='GithubRepository',
            new_name='Repository',
        ),
        migrations.DeleteModel(
            name='GithubAppUser',
        ),
        migrations.DeleteModel(
            name='GithubInstallationToken',
        ),
        migrations.DeleteModel(
            name='GithubUser',
        ),
        migrations.DeleteModel(
            name='GithubUserAccessToken',
        ),
        migrations.DeleteModel(
            name='GithubUserRefreshToken',
        ),
        migrations.AlterField(
            model_name='githubrepomap',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.appinstallation'),
        ),
        migrations.AlterField(
            model_name='monitoredpullrequest',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinstallation'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.appinstallation'),
        ),
        migrations.DeleteModel(
            name='GithubAppInstallation',
        ),
    ]
