# Generated by Django 4.0.4 on 2022-05-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('app', '0021_userrepoaccess'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='repository',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='socialaccount.socialapp'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('repo_id', 'app')},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
    ]
