# Generated by Django 4.0.4 on 2022-05-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('app', '0023_alter_githubrepomap_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GithubRepoMap',
            new_name='MonitoredRepositoryMap',
        ),
        migrations.AlterUniqueTogether(
            name='userrepoaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrepoaccess',
            name='access',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrepoaccess',
            name='social_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userrepoaccess',
            unique_together={('repository', 'social_account')},
        ),
        migrations.RemoveField(
            model_name='userrepoaccess',
            name='user',
        ),
    ]
