# Generated by Django 4.0.4 on 2022-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_userrepoaccess_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredpullrequest',
            name='integration',
        ),
        migrations.AlterField(
            model_name='userrepoaccess',
            name='access',
            field=models.IntegerField(choices=[('50', 'Owner'), ('40', 'Maintainer'), ('30', 'Developer'), ('20', 'Reporter'), ('10', 'Guest'), ('5', 'Minimal'), ('0', 'No Access')]),
        ),
    ]
