# Generated by Django 4.0.4 on 2022-06-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_monitoredpullrequest_integration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubAppToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('secret', models.CharField(max_length=200)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_token', to='app.appinstallation')),
            ],
        ),
    ]
